name: Deploy Backend

on:
  push:
    branches:
      - master  # Or any branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:latest
            # Stop and remove existing containers
            docker stop blog-backend || true
            docker rm blog-backend || true
  
            # Run the Docker container with the correct name and configuration
            docker run -d --name blog-backend -p 8081:8081 ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:latest
  
            # Clean up unused images
            docker image prune -f
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}